// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ-GAVIswE76xbSM82ORpfqh_NmMP1nJA',
    appId: '1:310291668478:web:522987fd64f87d6f4034af',
    messagingSenderId: '310291668478',
    projectId: 'cs4261assignment1',
    authDomain: 'cs4261assignment1.firebaseapp.com',
    databaseURL: 'https://cs4261assignment1-default-rtdb.firebaseio.com',
    storageBucket: 'cs4261assignment1.appspot.com',
    measurementId: 'G-MGZWW0CDE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ArFA7gGOhTgtfM7PBA7TUmx7e8qw938',
    appId: '1:310291668478:android:9e6d60a7af485c3f4034af',
    messagingSenderId: '310291668478',
    projectId: 'cs4261assignment1',
    databaseURL: 'https://cs4261assignment1-default-rtdb.firebaseio.com',
    storageBucket: 'cs4261assignment1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlGJw-VytkCTVK3t9oyScASzq3sYlkj0Q',
    appId: '1:310291668478:ios:7d5e7fabcff5b5b84034af',
    messagingSenderId: '310291668478',
    projectId: 'cs4261assignment1',
    databaseURL: 'https://cs4261assignment1-default-rtdb.firebaseio.com',
    storageBucket: 'cs4261assignment1.appspot.com',
    iosClientId: '310291668478-oratgcef351dkksc73dlh5nt1n932d24.apps.googleusercontent.com',
    iosBundleId: 'com.srikarviswanatha.practiceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlGJw-VytkCTVK3t9oyScASzq3sYlkj0Q',
    appId: '1:310291668478:ios:f2cab2736a9605df4034af',
    messagingSenderId: '310291668478',
    projectId: 'cs4261assignment1',
    databaseURL: 'https://cs4261assignment1-default-rtdb.firebaseio.com',
    storageBucket: 'cs4261assignment1.appspot.com',
    iosClientId: '310291668478-h0oumuaka8odb8r1dirn8gm98b3n6nhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceProject.RunnerTests',
  );
}
